// Generated by gencpp from file sysinfo/ostmsg.msg
// DO NOT EDIT!


#ifndef SYSINFO_MESSAGE_OSTMSG_H
#define SYSINFO_MESSAGE_OSTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sysinfo
{
template <class ContainerAllocator>
struct ostmsg_
{
  typedef ostmsg_<ContainerAllocator> Type;

  ostmsg_()
    : state(0)  {
    }
  ostmsg_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::sysinfo::ostmsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sysinfo::ostmsg_<ContainerAllocator> const> ConstPtr;

}; // struct ostmsg_

typedef ::sysinfo::ostmsg_<std::allocator<void> > ostmsg;

typedef boost::shared_ptr< ::sysinfo::ostmsg > ostmsgPtr;
typedef boost::shared_ptr< ::sysinfo::ostmsg const> ostmsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sysinfo::ostmsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sysinfo::ostmsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sysinfo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sysinfo': ['/home/thanos/Desktop/thesis/ros_workspace/src/sysinfo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sysinfo::ostmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sysinfo::ostmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sysinfo::ostmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sysinfo::ostmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sysinfo::ostmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sysinfo::ostmsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sysinfo::ostmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "800f34bc468def1d86e2d42bea5648c0";
  }

  static const char* value(const ::sysinfo::ostmsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x800f34bc468def1dULL;
  static const uint64_t static_value2 = 0x86e2d42bea5648c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::sysinfo::ostmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sysinfo/ostmsg";
  }

  static const char* value(const ::sysinfo::ostmsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sysinfo::ostmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 state\n\
";
  }

  static const char* value(const ::sysinfo::ostmsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sysinfo::ostmsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ostmsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sysinfo::ostmsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sysinfo::ostmsg_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSINFO_MESSAGE_OSTMSG_H
